General:
  KAFKA_BROKER_URL: kafka:9093
  KAFKA_CONSUMER_TIMEOUT_MS: 120000

1p_count_up:
  OUT_TOPIC:
    count: ./schema/count.avsc

2c_print_count:
  IN_TOPIC:
    count: ./schema/count.avsc
  IN_GROUP: count
