version: '2'
    
services:
  
  1c_postgres_db:
    container_name: 1c_postgres_db
    hostname: 1c_postgres_db
    image: postgres:alpine
    ports:
    - "5432:5432"
    volumes:
      - 1c_postgres_volume:/var/lib/postgresql/data
      - ./src/configurations/1c_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
  
networks:
  default:
    external:
      name: caai
      
volumes:
  1c_postgres_volume:
    external: true
