version: '2'

services:
  1p_count_up:
    container_name: 1p_count_up
    build:
      context: ./src
      dockerfile: Dockerfile_1p_count_up
    environment:
      KAFKA_BROKER_URL: kafka:9093
      OUT_TOPIC: count
      OUT_SCHEMA_FILE: ./schema/count.avsc

networks:
  default:
    external:
      name: caai
