version: '2'

services:
  2c_print_count:
    container_name: 2c_print_count
    build:
      context: ./src
      dockerfile: Dockerfile_2c_print_count
    environment:
      config_path: ./configurations/config.yml
      config_section: General, 2c_print_count

networks:
  default:
    external:
      name: caai
